@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class MesBundleFluxAlimentation{

             Bundle.type => [None..None]
             Bundle.entry => [1..None]
             Bundle.entry:mes-observation => [1..1]
             Bundle.entry:mes-observation.resource => [None..None]
             Bundle.entry:mes-observation.request => [1..None]
             Bundle.entry:mes-observation.request.method => [None..None]
             Bundle.entry:mes-observation.request.url => [None..None]
             Bundle.entry:mes-device => [0..1]
             Bundle.entry:mes-device.resource => [None..None]
             Bundle.entry:mes-device.request => [1..None]
             Bundle.entry:mes-device.request.method => [None..None]
             Bundle.entry:mes-device.request.url => [None..None]
        } 

        class MesFrObservationBmi{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
        } 

        class MesFrObservationBodyTemperature{

             Observation.meta.source => [None..None]
             Observation.extension:levelOfExertion => <&plus>[0..1]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x]:valueQuantity => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.bodySite => [None..None]
             Observation.bodySite.coding.system => [1..None]
             Observation.bodySite.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationBodyWeight{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x]:valueQuantity => [None..None]
             Observation.value[x]:valueQuantity.code => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationBodyHeight{

             Observation.meta.source => [None..None]
             Observation.extension:bodyposition => <&plus>[0..1]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x]:valueQuantity => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationBp{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.effective[x] => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..0]
             Observation.interpretation => [None..None]
             Observation.bodySite => [None..None]
             Observation.bodySite.coding.system => [1..None]
             Observation.bodySite.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
             Observation.component:SystolicBP => [None..None]
             Observation.component:SystolicBP.code.coding => [1..None]
             Observation.component:SystolicBP.value[x] => [None..None]
             Observation.component:DiastolicBP => [None..None]
             Observation.component:DiastolicBP.code.coding => [1..None]
             Observation.component:DiastolicBP.value[x] => [None..None]
             Observation.component:MeanBP => [0..1]
             Observation.component:MeanBP.code.coding => [1..None]
             Observation.component:MeanBP.code.coding:MBPCode => [1..1]
             Observation.component:MeanBP.code.coding:MBPCode.system => [1..None]
             Observation.component:MeanBP.code.coding:MBPCode.code => [1..None]
        } 

        class MesFrObservationHeartrate{

             Observation.meta.source => [None..None]
             Observation.extension:levelOfExertion => <&plus>[0..1]
             Observation.extension:bodyPosition => <&plus>[0..1]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.interpretation => [None..None]
             Observation.bodySite => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
        } 

        class MesFrObservationOxygenSat{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfoAdministrationOxygen => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.partOf => [None..1]
             Observation.partOf.reference => [None..None]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.bodySite => [None..None]
             Observation.method => [None..None]
             Observation.method.coding.system => [1..None]
             Observation.method.coding.code => [1..None]
             Observation.device => [None..None]
        } 

        class MesFrObservationRespiratoryRate{

             Observation => [None..None]
             Observation.meta.source => [None..None]
             Observation.extension:bodyPosition => <&plus>[0..1]
             Observation.extension:levelOfExertion => <&plus>[0..1]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.code.coding => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesObservationGlucose{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement => <&plus>[0..1]
             Observation.extension:MesMomentOfMeasurement.value[x] => <&plus>[None..None]
             Observation.extension:MesNumberOfDays => <&plus>[0..1]
             Observation.extension:MesDiabetisType => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.code => [None..None]
             Observation.code.coding.system => [1..None]
             Observation.code.coding.code => [1..None]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.effective[x] => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].value => [None..None]
             Observation.value[x].system => [1..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange.appliesTo => [None..None]
             Observation.referenceRange.appliesTo.coding.system => [1..None]
             Observation.referenceRange.appliesTo.coding.code => [1..None]
        } 

        class MesObservationHeadCircumference{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [2..None]
             Observation.code.coding:headCircumCode => [1..1]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x]:valueQuantity => [None..None]
             Observation.value[x]:valueQuantity.unit => [None..None]
        } 

        class MesObservationPainSeverity{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.category:VSCat => [None..None]
             Observation.category:VSCat.coding.display => [None..None]
             Observation.code.coding => [1..None]
             Observation.code.coding:painServerCode => [1..1]
             Observation.effective[x] => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].unit => [1..None]
             Observation.value[x].system => [None..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.bodySite => [None..None]
             Observation.method => [None..None]
        } 

        class MesObservationStepsByDay{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.code.coding:stepsBDCode => [1..1]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].unit => [1..None]
             Observation.value[x].system => [1..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
        } 

        class MesObservationWaistCircumference{

             Observation.meta.source => [None..None]
             Observation.extension:supportingInfo => <&plus>[0..1]
             Observation.extension:MesReasonForMeasurement => <&plus>[0..1]
             Observation.code.coding => [1..None]
             Observation.code.coding:waistCircumCode => [1..1]
             Observation.subject => [None..None]
             Observation.encounter => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.value[x].system => [1..None]
             Observation.value[x].code => [1..None]
             Observation.dataAbsentReason.coding.system => [1..None]
             Observation.dataAbsentReason.coding.code => [1..None]
             Observation.device => [None..None]
         }

     }
     package extension #paleturquoise {

     MesFrObservationBodyTemperature -[#black,dashed,thickness=2]-> MesLevelOfExertionExtension
     MesFrObservationBodyTemperature -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesFrObservationBodyWeight -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesFrObservationBodyHeight -[#black,dashed,thickness=2]-> MesBodyPositionExtExtension
     MesFrObservationBodyHeight -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesFrObservationBp -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesFrObservationBp -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesFrObservationHeartrate -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesFrObservationOxygenSat -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesFrObservationRespiratoryRate -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesMomentOfMeasurement
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesNumberOfDays
     MesObservationGlucose -[#black,dashed,thickness=2]-> MesDiabetisType
     MesObservationHeadCircumference -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationPainSeverity -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationStepsByDay -[#black,dashed,thickness=2]-> MesReasonForMeasurement
     MesObservationWaistCircumference -[#black,dashed,thickness=2]-> MesReasonForMeasurement

        class MesBodyPositionExtExtension{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class MesLevelOfExertionExtension{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class MesDiabetisType{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class MesMomentOfMeasurement{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
          Extension.value[x].coding => [None..1]
          Extension.value[x].coding.system => [1..None]
          Extension.value[x].coding.code => [1..None]
        } 
        class MesNumberOfDays{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
        } 
        class MesReasonForMeasurement{

          Extension.extension => [None..0]
          Extension.url => [None..None]
          Extension.value[x] => [None..None]
         }
     }
     package valueset #PaleVioletRed{

        class MesValueSetHeightBodyPosition  

     MesBodyPositionExtExtension -[#black,dotted,thickness=2]-> MesValueSetHeightBodyPosition

        class MethodeGlucoseVS  

     MesObservationGlucose -[#black,dotted,thickness=2]-> MethodeGlucoseVS
       }

package "Ressources de base" #palegreen {

 class "Bundle" as  class94c51f19c37f96ed231f5a0ae512b2a8 

    class94c51f19c37f96ed231f5a0ae512b2a8 --> MesBundleFluxAlimentation

 class "bmi" as  class810dc6911c825b55eff684098f2beb19 

    class810dc6911c825b55eff684098f2beb19 --> MesFrObservationBmi

 class "bodytemp" as  classaa5a81d6f7003d017ea7e6b41ad267e1 

    classaa5a81d6f7003d017ea7e6b41ad267e1 --> MesFrObservationBodyTemperature

 class "bodyweight" as  class42f266cb82c4cd680f97c9609fbd96e1 

    class42f266cb82c4cd680f97c9609fbd96e1 --> MesFrObservationBodyWeight

 class "bodyheight" as  classee160d1136ad35f95725456015231c04 

    classee160d1136ad35f95725456015231c04 --> MesFrObservationBodyHeight

 class "bp" as  class5cfdb867e96374c7883b31d6928cc4cb 

    class5cfdb867e96374c7883b31d6928cc4cb --> MesFrObservationBp

 class "heartrate" as  class9f0e20598fbb64e6492886a377f511b4 

    class9f0e20598fbb64e6492886a377f511b4 --> MesFrObservationHeartrate

 class "oxygensat" as  class7b8a7e51da4b89e163108c52f4754acc 

    class7b8a7e51da4b89e163108c52f4754acc --> MesFrObservationOxygenSat

 class "resprate" as  class61618b724e7eb165e5c54c81755777ae 

    class61618b724e7eb165e5c54c81755777ae --> MesFrObservationRespiratoryRate

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationGlucose

 class "headcircum" as  class79f4f12cb29f354faab97cf03e408d1c 

    class79f4f12cb29f354faab97cf03e408d1c --> MesObservationHeadCircumference

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationPainSeverity

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationStepsByDay

 class "vitalsigns" as  classbc3e6f566d4b627eb1169a15f6c63afa 

    classbc3e6f566d4b627eb1169a15f6c63afa --> MesObservationWaistCircumference
}
@enduml